# Generated by Django 4.2.17 on 2025-01-19 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='route',
        ),
        migrations.RemoveField(
            model_name='seat',
            name='version',
        ),
        migrations.AddField(
            model_name='seat',
            name='is_booked',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='booking',
            name='destination',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='booking',
            name='source',
            field=models.CharField(max_length=100),
        ),
    ]
